### PR TITLE
Added Inventory and Item class aswell as a Hover class to display tooltips

### PR DESCRIPTION
**Pull request by DavidPHH**
Summary of these commits:
- Changed Ground and Wall to use the .png images in res
- Item class with a simple parse function to read name and description from json string
- Hover class to implement tooltip on anything that should be hoverable
- Inventory class to draw the items in the player's inventory
- Moved files in /res/ to different folders within /res/

### CODE REVIEW

**Comment by AdrianWennberg** [comment]
I really like how this works! Do you have any credits for all the pictures?

**Comment by DavidPHH** [comment]
Made the hover.png one myself with assets from [here](https://opengameart.org/content/inventory) , no instructions for credits so I assumed free use (given the website)

**Comment by AdrianWennberg** [comment]
It's good to give credits anyway. What about the questionmark and the font?

**Review by AngryMajor — APPROVED** [review]
everything seems to work well

**Pull request merged**
