### PR TITLE
Added make_level function that draws a level from a file

### PR DESCRIPTION
**Pull request by DavidPHH**
-Only two 'scenery' classes at the moment: Wall & Ground
-Simple collision detection so player can't go through walls
-Map files should be 25x20 characters (WxH)

### CODE REVIEW

**Comment by AdrianWennberg** [comment]
Since the master branch has changed, we need to fix some stuff. I'll go ahead and do that now.

**Comment by DavidPHH** [comment]
it changed after this commit 🤔

**Comment by AdrianWennberg** [comment]
I've got it fixed. We just moved some files and changed how we load paths a bit.

**Review by AdrianWennberg — APPROVED** [review]
Looks all good! Next up is sprites and items.

**Pull request merged**
